version: '2'
services:
    jhipsterfirst-app:
        image: jhipsterfirst
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterfirst-postgresql:5432/jhipsterFirst
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterfirst-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterfirst-postgresql
