version: '2'
services:
    jhipsterfirst-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/jhipsterFirst/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipsterFirst
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
